apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: k8sdcs.ibmcloudappmgmt.com
spec:
  group: ibmcloudappmgmt.com
  names:
    kind: K8sDC
    listKind: K8sDCList
    plural: k8sdcs
    singular: k8sdc
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
